path: /dataset
train: bdd100k_labels_release/bdd100k/train.txt 
val:  bdd100k_labels_release/bdd100k/val.txt 

# Classes
names:
  0: person
  1: rider
  2: car
  3: bus
  4: truck
  5: bike
  6: motor
  7: train
  8: traffic sign
  9: traffic light