path: /home/danish/danish/datasets/assignment_data_bdd/bdd100k_images_100k/bdd100k/images/100k
train: /home/danish/danish/datasets/assignment_data_bdd/bdd100k_labels_release/bdd100k/train.txt 
val: /home/danish/danish/datasets/assignment_data_bdd/bdd100k_labels_release/bdd100k/val.txt 

# Classes
names:
  0: pedestrian
  1: rider
  2: car
  3: truck
  4: bus
  5: train
  6: motor
  7: bicycle
  8: traffic light
  9: traffic sign